### ISSUE TITLE
Any updates you'd like done?

### ISSUE THREAD

**Issue by BrianRossmajer** [draegtun/PerlX-QuoteOperator#1]
Hi,

I entered the CPAN github pull request challenge: http://perlmaven.com/2015-cpan-pull-request-challenge and was assigned PerlX-QuoteOperator...  so I'd like to try to contribute to the module.

I had a quick look at the rt tickets, and could implement the removal of Directory::Scratch if you like; it's a deprecated module so that might be a good step.  Swapping HTTP::TIny for LWP::Simple is easily done, but breaks functionality as HTTP::Tiny does not support many URL types that LWP::Simple does support.

Is there anything you'd like to see done?

**Comment by draegtun** [comment]
Hi @BrianRossmajer,

You're the second CPAN-pull-requeste-challenger I've had who wanted to update this module :)

I stopped the first _challenger_ because the real requirement from those RT tickets is to reduce the dependencies on PerlX::QuoteOperator and as such the PerlX::QuoteOperator::URL really shouldn't be part of this distro.

Unfortunately I've sat on it for a while because I decided what I really wanted was just to have the actual engine sitting under the PerlX::QuoteOperator namespace and put anything that uses it under the QuoteOperator namespace (https://github.com/draegtun/QuoteOperator - though nothing to actually see there yet!)  

Anyway to keep the ball rolling towards that I've done the following...
- Ripped PerlX::QuoteOperator::URL out
- So PerlX::QuoteOperator no longer needs Directory::Scratch or LWP::Simple (0.06 uploaded to CPAN)
- Both those RT wishes will shortly be closed (https://rt.cpan.org/Ticket/Display.html?id=81392 & https://rt.cpan.org/Ticket/Display.html?id=81393)
- new separate PerlX::QuoteOperator::URL module but will continue to use LWP::Simple for backward compatibility (1.00 uploaded to CPAN)

So nothing todo on PerlX::QuoteOperator so I'll be closing this comment.   At some point in future I'll be looking to create QuoteOperator::URL which will (probably) use HTTP::Tiny (for even better have the option to switch between different HTTP clients).

However one thing you did bring to my attention was that Directory::Scratch is now deprecated.    I've left it in new PerlX::QuoteOperator::URL tests for now.  If you fancy changing that then please submit a PR there - https://github.com/draegtun/PerlX-QuoteOperator-URL 

Many thanks for your interest.   All the best with whatever CPAN-Pull-request you do get your hands on.

Kind regards,

Barry
